export const QUESTIONS = [
  // 1-10: Comportamento e Atitude
  {
    id: 1,
    text: "Como você vai à padaria?",
    answers: [
      { text: "🩲 De cueca/sunga mesmo", points: 0 },
      { text: "👕 Qualquer trapo velho", points: 1 },
      { text: "👔 Troco de roupa rápido", points: 2 },
      { text: "👗 Escolho roupa com cuidado", points: 3 },
      { text: "💃 Monto look completo com acessórios", points: 4 },
    ],
  },
  {
    id: 2,
    text: "Qual seu shampoo?",
    answers: [
      { text: "🧼 Sabonete serve pra tudo", points: 0 },
      { text: "🚿 Shampoo 3 em 1", points: 1 },
      { text: "💆 Shampoo e condicionador", points: 2 },
      { text: "✨ Produtos específicos pro meu cabelo", points: 3 },
      { text: "💅 Rotina completa de skincare", points: 4 },
    ],
  },
  {
    id: 3,
    text: "Como você fala?",
    answers: [
      { text: "💪 Mano, véi, brother", points: 0 },
      { text: "🗣️ Cara, tipo assim", points: 1 },
      { text: "😐 Falo normal", points: 2 },
      { text: "💁 Amiga, querida", points: 3 },
      { text: "💋 Lacrou, arrasa, diva", points: 4 },
    ],
  },
  {
    id: 4,
    text: "Reação a um elogio:",
    answers: [
      { text: "😳 Fico sem graça, não sei responder", points: 0 },
      { text: "👍 Falo 'valeu' e pronto", points: 1 },
      { text: "😊 Agradeço educadamente", points: 2 },
      { text: "💁 Agradeço e faço pose", points: 3 },
      { text: "👑 Já sabia, mas obrigado!", points: 4 },
    ],
  },
  {
    id: 5,
    text: "Sua bebida preferida:",
    answers: [
      { text: "🍺 Cerveja gelada", points: 0 },
      { text: "🥃 Whisky puro", points: 1 },
      { text: "🍹 Drink qualquer", points: 2 },
      { text: "🍸 Gin tônica", points: 3 },
      { text: "🌈 Drink colorido com guarda-chuva", points: 4 },
    ],
  },
  {
    id: 6,
    text: "Assunto de conversa:",
    answers: [
      { text: "⚽ Futebol, carro, cerveja", points: 0 },
      { text: "💼 Trabalho, política", points: 1 },
      { text: "🎬 Filmes, séries", points: 2 },
      { text: "👗 Fofoca, moda", points: 3 },
      { text: "👑 RuPaul, Beyoncé, lacração", points: 4 },
    ],
  },
  {
    id: 7,
    text: "Como você chora:",
    answers: [
      { text: "😤 Homem não chora", points: 0 },
      { text: "⚰️ Só em velório", points: 1 },
      { text: "😢 Às vezes, sozinho", points: 2 },
      { text: "😭 Choro vendo filme", points: 3 },
      { text: "💦 Choro por qualquer coisa", points: 4 },
    ],
  },
  {
    id: 8,
    text: "Reação ao ver aranha:",
    answers: [
      { text: "✋ Pego com a mão e jogo fora", points: 0 },
      { text: "👞 Mato com chinelo", points: 1 },
      { text: "📞 Chamo alguém para matar", points: 2 },
      { text: "😱 Grito e subo na cadeira", points: 3 },
      { text: "🏃 Saio correndo e gritando", points: 4 },
    ],
  },
  {
    id: 9,
    text: "Como você dança:",
    answers: [
      { text: "🧍 Fico parado no canto", points: 0 },
      { text: "🕺 Só se tiver muito bêbado", points: 1 },
      { text: "💃 Danço normal", points: 2 },
      { text: "🎉 Danço todas as músicas", points: 3 },
      { text: "✨ Sou o centro da pista", points: 4 },
    ],
  },
  {
    id: 10,
    text: "Sua cor favorita:",
    answers: [
      { text: "⚫ Preto", points: 0 },
      { text: "🔵 Azul escuro", points: 1 },
      { text: "🟢 Verde", points: 2 },
      { text: "🟣 Roxo", points: 3 },
      { text: "🌈 Rosa choque", points: 4 },
    ],
  },

  // 11-20: Cultura Pop e Entretenimento
  {
    id: 11,
    text: "Sua série favorita:",
    answers: [
      { text: "🎬 Breaking Bad", points: 0 },
      { text: "🔫 Peaky Blinders", points: 1 },
      { text: "👑 Game of Thrones", points: 2 },
      { text: "💄 Euphoria", points: 3 },
      { text: "👸 RuPaul's Drag Race", points: 4 },
    ],
  },
  {
    id: 12,
    text: "Filme que você ama:",
    answers: [
      { text: "💥 Velozes e Furiosos", points: 0 },
      { text: "🦇 Batman", points: 1 },
      { text: "🌌 Star Wars", points: 2 },
      { text: "💕 La La Land", points: 3 },
      { text: "👠 Priscilla, A Rainha do Deserto", points: 4 },
    ],
  },
  {
    id: 13,
    text: "Sua opinião sobre BBB:",
    answers: [
      { text: "📺 Não assisto essa porcaria", points: 0 },
      { text: "🤷 Não me interessa", points: 1 },
      { text: "👀 Vejo os memes", points: 2 },
      { text: "📱 Assisto quando dá", points: 3 },
      { text: "🔥 Sou fã, voto todo dia", points: 4 },
    ],
  },
  {
    id: 14,
    text: "Beyoncé é:",
    answers: [
      { text: "🎤 Cantora normal", points: 0 },
      { text: "👍 Boa cantora", points: 1 },
      { text: "⭐ Muito talentosa", points: 2 },
      { text: "👑 Rainha", points: 3 },
      { text: "🙏 Deusa suprema", points: 4 },
    ],
  },
  {
    id: 15,
    text: "Lady Gaga é:",
    answers: [
      { text: "🎵 Cantora ok", points: 0 },
      { text: "🎶 Tem umas músicas boas", points: 1 },
      { text: "⭐ Muito talentosa", points: 2 },
      { text: "👸 Ícone pop", points: 3 },
      { text: "🌟 Minha mãe espiritual", points: 4 },
    ],
  },
  {
    id: 16,
    text: "Pabllo Vittar:",
    answers: [
      { text: "❌ Não conheço", points: 0 },
      { text: "🤔 Já ouvi falar", points: 1 },
      { text: "🎵 Tem umas músicas boas", points: 2 },
      { text: "💃 Amo as músicas", points: 3 },
      { text: "👑 É a rainha do Brasil", points: 4 },
    ],
  },
  {
    id: 17,
    text: "Anitta é:",
    answers: [
      { text: "🙄 Superestimada", points: 0 },
      { text: "🎤 Cantora ok", points: 1 },
      { text: "💃 Muito talentosa", points: 2 },
      { text: "🌎 Orgulho nacional", points: 3 },
      { text: "👑 Rainha da América Latina", points: 4 },
    ],
  },
  {
    id: 18,
    text: "Sua reação a fofoca:",
    answers: [
      { text: "😒 Não ligo", points: 0 },
      { text: "🤷 Tanto faz", points: 1 },
      { text: "👂 Escuto se for interessante", points: 2 },
      { text: "☕ Adoro ouvir", points: 3 },
      { text: "📢 Sou o centro da fofoca", points: 4 },
    ],
  },
  {
    id: 19,
    text: "Astrologia é:",
    answers: [
      { text: "🔭 Bobagem", points: 0 },
      { text: "🤷 Não acredito", points: 1 },
      { text: "⭐ Interessante", points: 2 },
      { text: "🌙 Acredito sim", points: 3 },
      { text: "✨ Meu mapa astral explica tudo", points: 4 },
    ],
  },
  {
    id: 20,
    text: "Seu emoji mais usado:",
    answers: [
      { text: "👍", points: 0 },
      { text: "😂", points: 1 },
      { text: "❤️", points: 2 },
      { text: "💅", points: 3 },
      { text: "💋", points: 4 },
    ],
  },

  // 21-30: Situações do Dia a Dia
  {
    id: 21,
    text: "Pneu furado:",
    answers: [
      { text: "🔧 Troco sozinho", points: 0 },
      { text: "📞 Chamo alguém pra ajudar", points: 1 },
      { text: "🚗 Ligo pro guincho", points: 2 },
      { text: "😰 Entro em pânico", points: 3 },
      { text: "💅 Nem sei onde fica o estepe", points: 4 },
    ],
  },
  {
    id: 22,
    text: "Barata na cozinha:",
    answers: [
      { text: "🔥 Toco fogo", points: 0 },
      { text: "👞 Mato com chinelo", points: 1 },
      { text: "😰 Chamo alguém", points: 2 },
      { text: "😱 Grito e saio correndo", points: 3 },
      { text: "🏃 Mudo de casa", points: 4 },
    ],
  },
  {
    id: 23,
    text: "Como você tira selfie:",
    answers: [
      { text: "🤳 Rápido e sem pose", points: 0 },
      { text: "📸 Normal, sem frescura", points: 1 },
      { text: "😊 Com um sorriso", points: 2 },
      { text: "💁 Várias poses e ângulos", points: 3 },
      { text: "✨ Sessão de fotos completa", points: 4 },
    ],
  },
  {
    id: 24,
    text: "Filhote de cachorro:",
    answers: [
      { text: "👍 Bonitinho", points: 0 },
      { text: "😊 Que fofo", points: 1 },
      { text: "🥰 Amo cachorrinhos", points: 2 },
      { text: "😍 Quero pegar no colo", points: 3 },
      { text: "💕 Derrete meu coração", points: 4 },
    ],
  },
  {
    id: 25,
    text: "Presente que não gostou:",
    answers: [
      { text: "😒 Falo na cara", points: 0 },
      { text: "🤷 Deixo de lado", points: 1 },
      { text: "😊 Agradeço mesmo assim", points: 2 },
      { text: "💕 Agradeço efusivamente", points: 3 },
      { text: "🎭 Finjo que amei", points: 4 },
    ],
  },
  {
    id: 26,
    text: "Alguém fala 'eu te amo':",
    answers: [
      { text: "😬 'Valeu'", points: 0 },
      { text: "👍 'Eu também'", points: 1 },
      { text: "😊 'Eu te amo também'", points: 2 },
      { text: "💕 'Amo você demais'", points: 3 },
      { text: "💋 'Você é tudo pra mim'", points: 4 },
    ],
  },
  {
    id: 27,
    text: "Filme de terror:",
    answers: [
      { text: "😴 Durmo no meio", points: 0 },
      { text: "😐 Assisto normal", points: 1 },
      { text: "😰 Fico tenso", points: 2 },
      { text: "😱 Grito nas partes de susto", points: 3 },
      { text: "🙈 Fecho os olhos o tempo todo", points: 4 },
    ],
  },
  {
    id: 28,
    text: "Como você cumprimenta amigos:",
    answers: [
      { text: "🤝 Aperto de mão", points: 0 },
      { text: "👊 Soco no ombro", points: 1 },
      { text: "🤗 Abraço", points: 2 },
      { text: "💋 Beijinho no rosto", points: 3 },
      { text: "💕 Abraço apertado e grito", points: 4 },
    ],
  },
  {
    id: 29,
    text: "Animal de estimação ideal:",
    answers: [
      { text: "🐕 Pitbull", points: 0 },
      { text: "🐶 Cachorro grande", points: 1 },
      { text: "🐱 Gato", points: 2 },
      { text: "🐩 Poodle", points: 3 },
      { text: "🐾 Chihuahua de lacinho", points: 4 },
    ],
  },
  {
    id: 30,
    text: "Casal gay se beijando:",
    answers: [
      { text: "😒 Viro a cara", points: 0 },
      { text: "😐 Tanto faz", points: 1 },
      { text: "😊 Acho normal", points: 2 },
      { text: "💕 Acho lindo", points: 3 },
      { text: "📸 Tiro foto pra postar", points: 4 },
    ],
  },

  // 31-40: Estilo e Aparência
  {
    id: 31,
    text: "Como você escolhe roupa:",
    answers: [
      { text: "👕 Pego a primeira que vejo", points: 0 },
      { text: "👔 Qualquer uma limpa", points: 1 },
      { text: "👗 Penso um pouco", points: 2 },
      { text: "💄 Combino cores e estilo", points: 3 },
      { text: "✨ Monto look completo", points: 4 },
    ],
  },
  {
    id: 32,
    text: "Seu perfume:",
    answers: [
      { text: "🚫 Não uso", points: 0 },
      { text: "🧴 Desodorante resolve", points: 1 },
      { text: "💨 Uso perfume básico", points: 2 },
      { text: "✨ Tenho perfume bom", points: 3 },
      { text: "💎 Coleção de perfumes importados", points: 4 },
    ],
  },
  {
    id: 33,
    text: "Cuidado com as unhas:",
    answers: [
      { text: "🔪 Corto com dente", points: 0 },
      { text: "✂️ Corto quando lembro", points: 1 },
      { text: "💅 Corto regularmente", points: 2 },
      { text: "✨ Faço as unhas", points: 3 },
      { text: "💎 Manicure toda semana", points: 4 },
    ],
  },
  {
    id: 34,
    text: "Seu cabelo:",
    answers: [
      { text: "✂️ Corto em casa", points: 0 },
      { text: "💈 Barbeiro básico", points: 1 },
      { text: "💇 Salão normal", points: 2 },
      { text: "✨ Salão bom", points: 3 },
      { text: "💎 Cabeleireiro famoso", points: 4 },
    ],
  },
  {
    id: 35,
    text: "Acessórios:",
    answers: [
      { text: "⌚ Só relógio", points: 0 },
      { text: "👔 Relógio e cinto", points: 1 },
      { text: "💍 Alguns acessórios", points: 2 },
      { text: "✨ Vários acessórios", points: 3 },
      { text: "💎 Cheio de acessórios", points: 4 },
    ],
  },
  {
    id: 36,
    text: "Roupa pra dormir:",
    answers: [
      { text: "🩲 Cueca", points: 0 },
      { text: "👕 Camiseta velha", points: 1 },
      { text: "🛌 Pijama normal", points: 2 },
      { text: "✨ Pijama bonito", points: 3 },
      { text: "💎 Robe de seda", points: 4 },
    ],
  },
  {
    id: 37,
    text: "Tatuagem:",
    answers: [
      { text: "💪 Tribal/caveira", points: 0 },
      { text: "🦅 Águia/leão", points: 1 },
      { text: "🌹 Algo significativo", points: 2 },
      { text: "✨ Algo delicado", points: 3 },
      { text: "🦋 Borboleta/flor", points: 4 },
    ],
  },
  {
    id: 38,
    text: "Seu estilo de roupa:",
    answers: [
      { text: "👕 Camiseta e bermuda", points: 0 },
      { text: "👔 Casual masculino", points: 1 },
      { text: "👗 Moderno", points: 2 },
      { text: "✨ Fashion", points: 3 },
      { text: "💎 Extravagante", points: 4 },
    ],
  },
  {
    id: 39,
    text: "Maquiagem:",
    answers: [
      { text: "❌ Jamais", points: 0 },
      { text: "🚫 Não é pra mim", points: 1 },
      { text: "🤔 Talvez em festa", points: 2 },
      { text: "✨ Uso às vezes", points: 3 },
      { text: "💄 Uso sempre", points: 4 },
    ],
  },
  {
    id: 40,
    text: "Sua bolsa/mochila:",
    answers: [
      { text: "🎒 Mochila preta", points: 0 },
      { text: "💼 Mochila/mala normal", points: 1 },
      { text: "👜 Bolsa discreta", points: 2 },
      { text: "✨ Bolsa estilosa", points: 3 },
      { text: "💎 Bolsa de grife", points: 4 },
    ],
  },

  // 41-50: Situações Específicas e Atração
  {
    id: 41,
    text: "Negão na praia de nudismo:",
    answers: [
      { text: "🙈 Furo meus olhos", points: 0 },
      { text: "😐 Olho discretamente", points: 1 },
      { text: "👀 Dou uma olhadinha", points: 2 },
      { text: "😍 Olho bastante", points: 3 },
      { text: "📸 Peço o Instagram", points: 4 },
    ],
  },
  {
    id: 42,
    text: "Channing Tatum sem camisa:",
    answers: [
      { text: "💪 'Preciso malhar'", points: 0 },
      { text: "😶 'O cara é bonito'", points: 1 },
      { text: "😳 Olho mais tempo que deveria", points: 2 },
      { text: "🤤 Salvo a foto", points: 3 },
      { text: "😍 Viro fã", points: 4 },
    ],
  },
  {
    id: 43,
    text: "Vestiário da academia:",
    answers: [
      { text: "🏃 Troco olhando pra parede", points: 0 },
      { text: "😐 Troco normal", points: 1 },
      { text: "👁️ Dou uma conferida discreta", points: 2 },
      { text: "👀 Olho bastante", points: 3 },
      { text: "🎭 Faço desfile", points: 4 },
    ],
  },
  {
    id: 44,
    text: "Amigo te chama de 'gato':",
    answers: [
      { text: "😠 Fico bravo", points: 0 },
      { text: "😐 Ignoro", points: 1 },
      { text: "😊 Agradeço", points: 2 },
      { text: "💁 'Eu sei'", points: 3 },
      { text: "💋 'Você também'", points: 4 },
    ],
  },
  {
    id: 45,
    text: "Música na balada:",
    answers: [
      { text: "🎸 Rock/sertanejo", points: 0 },
      { text: "🎵 Qualquer uma", points: 1 },
      { text: "💃 Pop", points: 2 },
      { text: "✨ Diva pop", points: 3 },
      { text: "🌈 Gloria Gaynor", points: 4 },
    ],
  },
  {
    id: 46,
    text: "Roupa de academia:",
    answers: [
      { text: "👕 Camiseta velha", points: 0 },
      { text: "👔 Roupa normal", points: 1 },
      { text: "💪 Roupa de treino", points: 2 },
      { text: "✨ Conjunto estiloso", points: 3 },
      { text: "💎 Look completo de marca", points: 4 },
    ],
  },
  {
    id: 47,
    text: "Seu ídolo:",
    answers: [
      { text: "⚽ Cristiano Ronaldo", points: 0 },
      { text: "🎬 Ator de ação", points: 1 },
      { text: "🎤 Cantor pop", points: 2 },
      { text: "👑 Diva pop", points: 3 },
      { text: "✨ RuPaul", points: 4 },
    ],
  },
  {
    id: 48,
    text: "Seu drink no bar:",
    answers: [
      { text: "🍺 Cerveja", points: 0 },
      { text: "🥃 Whisky", points: 1 },
      { text: "🍹 Caipirinha", points: 2 },
      { text: "🍸 Drink elaborado", points: 3 },
      { text: "🌈 Drink rosa com glitter", points: 4 },
    ],
  },
  {
    id: 49,
    text: "Morango do Nordeste:",
    answers: [
      { text: "🤢 Prefiro rock", points: 0 },
      { text: "🤷 Não conheço", points: 1 },
      { text: "🎵 É pegajoso", points: 2 },
      { text: "💃 Gosto sim", points: 3 },
      { text: "🔥 Amo demais", points: 4 },
    ],
  },
  {
    id: 50,
    text: "Final do quiz:",
    answers: [
      { text: "👍 Legal", points: 0 },
      { text: "😊 Gostei", points: 1 },
      { text: "💕 Adorei", points: 2 },
      { text: "✨ Amei demais", points: 3 },
      { text: "🌈 Lacrou", points: 4 },
    ],
  },
];
