#!/usr/bin/env bash
# Script to add PostgreSQL database to Railway project

echo "🔧 Adding PostgreSQL database to Railway project..."
echo ""
echo "⚠️  IMPORTANT: Railway CLI requires interactive mode for adding databases."
echo ""
echo "Please follow these steps:"
echo "1. Open your Railway project dashboard:"
echo "   https://railway.com/project/1ce4c5a0-0044-4b31-b2c4-dce9e43ded73?environmentId=8b0131d3-4396-49ef-a95f-b7c3e6f09dee"
echo ""
echo "2. Click 'New' → 'Database' → 'PostgreSQL'"
echo ""
echo "3. Railway will automatically:"
echo "   - Provision the PostgreSQL database"
echo "   - Set the DATABASE_URL environment variable"
echo "   - Connect it to your web service"
echo ""
echo "4. After adding the database, the web service will automatically redeploy"
echo ""
echo "📊 Project URL: https://railway.com/project/1ce4c5a0-0044-4b31-b2c4-dce9e43ded73"
echo ""
